<?php 

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group(array(
    'key' => 'group_58eb301ecb36a',
    'title' => 'Form',
    'fields' => array(
        0 => array(
            'key' => 'field_58f5c009ee909',
            'label' => __('Form fields', 'modularity-form-builder'),
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
        ),
        1 => array(
            'key' => 'field_58eb302883a68',
            'label' => __('Fields', 'modularity-form-builder'),
            'name' => 'form_fields',
            'type' => 'flexible_content',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'button_label' => 'Add form field',
            'min' => 1,
            'max' => '',
            'layouts' => array(
                0 => array(
                    'key' => '58eb3033e588f',
                    'name' => 'sender',
                    'label' => 'Sender',
                    'display' => 'block',
                    'sub_fields' => array(
                        0 => array(
                            'key' => 'field_58eb3944f7086',
                            'label' => __('Fields to display', 'modularity-form-builder'),
                            'name' => 'fields',
                            'type' => 'checkbox',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '50',
                                'class' => '',
                                'id' => '',
                            ),
                            'layout' => 'vertical',
                            'choices' => array(
                                'firstname' => __('Firstname', 'modularity-form-builder'),
                                'lastname' => __('Lastname', 'modularity-form-builder'),
                                'email' => __('Email', 'modularity-form-builder'),
                                'phone' => __('Phone', 'modularity-form-builder'),
                                'address' => __('Address', 'modularity-form-builder'),
                            ),
                            'default_value' => array(
                                0 => 'firstname',
                                1 => 'lastname',
                                2 => 'email',
                            ),
                            'allow_custom' => 0,
                            'save_custom' => 0,
                            'toggle' => 0,
                            'return_format' => 'value',
                        ),
                        1 => array(
                            'key' => 'field_58eb3a9bf7087',
                            'label' => __('Required fields', 'modularity-form-builder'),
                            'name' => 'required_fields',
                            'type' => 'checkbox',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '50',
                                'class' => '',
                                'id' => '',
                            ),
                            'layout' => 'vertical',
                            'choices' => array(
                                'firstname' => __('Firstname', 'modularity-form-builder'),
                                'lastname' => __('Lastname', 'modularity-form-builder'),
                                'email' => __('Email', 'modularity-form-builder'),
                                'phone' => __('Phone', 'modularity-form-builder'),
                                'address' => __('Address', 'modularity-form-builder'),
                            ),
                            'default_value' => array(
                                0 => 'firstname',
                                1 => 'lastname',
                                2 => 'email',
                            ),
                            'allow_custom' => 0,
                            'save_custom' => 0,
                            'toggle' => 0,
                            'return_format' => 'value',
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
                1 => array(
                    'key' => '58eb3f2cd914a',
                    'name' => 'message',
                    'label' => 'Message',
                    'display' => 'block',
                    'sub_fields' => array(
                        0 => array(
                            'key' => 'field_58eb3f37d914b',
                            'label' => __('Field label', 'modularity-form-builder'),
                            'name' => 'label',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => 'Message',
                            'maxlength' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                        ),
                        1 => array(
                            'key' => 'field_58eb3f5ed914c',
                            'label' => __('Required', 'modularity-form-builder'),
                            'name' => 'required',
                            'type' => 'true_false',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => 0,
                            'message' => __('Required field', 'modularity-form-builder'),
                            'ui' => 0,
                            'ui_on_text' => '',
                            'ui_off_text' => '',
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
                2 => array(
                    'key' => '58eb552a8189e',
                    'name' => 'input',
                    'label' => 'Input',
                    'display' => 'block',
                    'sub_fields' => array(
                        0 => array(
                            'key' => 'field_58eb55338189f',
                            'label' => __('Field label', 'modularity-form-builder'),
                            'name' => 'label',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'maxlength' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                        ),
                        1 => array(
                            'key' => 'field_58eb5547818a0',
                            'label' => __('Field value type', 'modularity-form-builder'),
                            'name' => 'value_type',
                            'type' => 'select',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'multiple' => 0,
                            'allow_null' => 0,
                            'choices' => array(
                                'text' => __('Text', 'modularity-form-builder'),
                                'number' => __('Number', 'modularity-form-builder'),
                                'email' => __('Email', 'modularity-form-builder'),
                                'tel' => __('Phone number', 'modularity-form-builder'),
                                'color' => __('Color', 'modularity-form-builder'),
                                'date' => __('Date', 'modularity-form-builder'),
                                'month' => __('Month', 'modularity-form-builder'),
                                'week' => __('Week', 'modularity-form-builder'),
                                'range' => __('Range', 'modularity-form-builder'),
                                'search' => __('Search', 'modularity-form-builder'),
                                'time' => __('Time', 'modularity-form-builder'),
                                'url' => __('Url', 'modularity-form-builder'),
                            ),
                            'default_value' => array(
                            ),
                            'ui' => 0,
                            'ajax' => 0,
                            'placeholder' => '',
                            'return_format' => 'value',
                        ),
                        2 => array(
                            'key' => 'field_58eb572440304',
                            'label' => __('Min value', 'modularity-form-builder'),
                            'name' => 'min_value',
                            'type' => 'number',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => array(
                                0 => array(
                                    0 => array(
                                        'field' => 'field_58eb5547818a0',
                                        'operator' => '==',
                                        'value' => 'number',
                                    ),
                                ),
                                1 => array(
                                    0 => array(
                                        'field' => 'field_58eb5547818a0',
                                        'operator' => '==',
                                        'value' => 'range',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '33.3333',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'min' => '',
                            'max' => '',
                            'step' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                        ),
                        3 => array(
                            'key' => 'field_58eb574140305',
                            'label' => __('Max value', 'modularity-form-builder'),
                            'name' => 'max_value',
                            'type' => 'number',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => array(
                                0 => array(
                                    0 => array(
                                        'field' => 'field_58eb5547818a0',
                                        'operator' => '==',
                                        'value' => 'number',
                                    ),
                                ),
                                1 => array(
                                    0 => array(
                                        'field' => 'field_58eb5547818a0',
                                        'operator' => '==',
                                        'value' => 'range',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '33.3333',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'min' => '',
                            'max' => '',
                            'step' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                        ),
                        4 => array(
                            'key' => 'field_58eb57a645640',
                            'label' => __('Step', 'modularity-form-builder'),
                            'name' => 'step',
                            'type' => 'number',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => array(
                                0 => array(
                                    0 => array(
                                        'field' => 'field_58eb5547818a0',
                                        'operator' => '==',
                                        'value' => 'number',
                                    ),
                                ),
                                1 => array(
                                    0 => array(
                                        'field' => 'field_58eb5547818a0',
                                        'operator' => '==',
                                        'value' => 'range',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '33.3333',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'min' => '',
                            'max' => '',
                            'step' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                        ),
                        5 => array(
                            'key' => 'field_58eb62d1ec890',
                            'label' => __('Min date', 'modularity-form-builder'),
                            'name' => 'min_value',
                            'type' => 'date_picker',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => array(
                                0 => array(
                                    0 => array(
                                        'field' => 'field_58eb5547818a0',
                                        'operator' => '==',
                                        'value' => 'date',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '50',
                                'class' => '',
                                'id' => '',
                            ),
                            'display_format' => 'Y-m-d',
                            'return_format' => 'Y-m-d',
                            'first_day' => 1,
                        ),
                        6 => array(
                            'key' => 'field_58eb62feec891',
                            'label' => __('Max date', 'modularity-form-builder'),
                            'name' => 'max_value',
                            'type' => 'date_picker',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => array(
                                0 => array(
                                    0 => array(
                                        'field' => 'field_58eb5547818a0',
                                        'operator' => '==',
                                        'value' => 'date',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '50',
                                'class' => '',
                                'id' => '',
                            ),
                            'display_format' => 'Y-m-d',
                            'return_format' => 'Y-m-d',
                            'first_day' => 1,
                        ),
                        7 => array(
                            'key' => 'field_58eb5614c5514',
                            'label' => __('Required', 'modularity-form-builder'),
                            'name' => 'required',
                            'type' => 'true_false',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => 0,
                            'message' => __('Required', 'modularity-form-builder'),
                            'ui' => 0,
                            'ui_on_text' => '',
                            'ui_off_text' => '',
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
                3 => array(
                    'key' => '58eb670839fee',
                    'name' => 'radio',
                    'label' => 'Radio',
                    'display' => 'block',
                    'sub_fields' => array(
                        0 => array(
                            'key' => 'field_58eb675039ff1',
                            'label' => __('Field label', 'modularity-form-builder'),
                            'name' => 'label',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'maxlength' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                        ),
                        1 => array(
                            'key' => 'field_58eb670d39fef',
                            'label' => __('Field values', 'modularity-form-builder'),
                            'name' => 'values',
                            'type' => 'repeater',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'min' => 2,
                            'max' => 0,
                            'layout' => 'table',
                            'button_label' => '',
                            'collapsed' => '',
                            'sub_fields' => array(
                                0 => array(
                                    'key' => 'field_58eb672c39ff0',
                                    'label' => __('Value', 'modularity-form-builder'),
                                    'name' => 'value',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'maxlength' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                ),
                            ),
                        ),
                        2 => array(
                            'key' => 'field_58eb699755795',
                            'label' => __('Required', 'modularity-form-builder'),
                            'name' => 'required',
                            'type' => 'true_false',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => 0,
                            'message' => __('Required', 'modularity-form-builder'),
                            'ui' => 0,
                            'ui_on_text' => '',
                            'ui_off_text' => '',
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
                4 => array(
                    'key' => '58eb6b023b076',
                    'name' => 'checkbox',
                    'label' => 'Checkbox',
                    'display' => 'block',
                    'sub_fields' => array(
                        0 => array(
                            'key' => 'field_58eb6b023b077',
                            'label' => __('Field label', 'modularity-form-builder'),
                            'name' => 'label',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'maxlength' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                        ),
                        1 => array(
                            'key' => 'field_58eb6b023b078',
                            'label' => __('Field values', 'modularity-form-builder'),
                            'name' => 'values',
                            'type' => 'repeater',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'min' => 1,
                            'max' => 0,
                            'layout' => 'table',
                            'button_label' => '',
                            'collapsed' => '',
                            'sub_fields' => array(
                                0 => array(
                                    'key' => 'field_58eb6b023b079',
                                    'label' => __('Value', 'modularity-form-builder'),
                                    'name' => 'value',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'maxlength' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                ),
                            ),
                        ),
                        2 => array(
                            'key' => 'field_58eb6b023b07a',
                            'label' => __('Required', 'modularity-form-builder'),
                            'name' => 'required',
                            'type' => 'true_false',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => 0,
                            'message' => __('Required', 'modularity-form-builder'),
                            'ui' => 0,
                            'ui_on_text' => '',
                            'ui_off_text' => '',
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
                5 => array(
                    'key' => '58eb6bd234c19',
                    'name' => 'select',
                    'label' => 'Select',
                    'display' => 'block',
                    'sub_fields' => array(
                        0 => array(
                            'key' => 'field_58eb6bd334c1a',
                            'label' => __('Field label', 'modularity-form-builder'),
                            'name' => 'label',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'maxlength' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                        ),
                        1 => array(
                            'key' => 'field_58eb6bd334c1b',
                            'label' => __('Field values', 'modularity-form-builder'),
                            'name' => 'values',
                            'type' => 'repeater',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'min' => 1,
                            'max' => 0,
                            'layout' => 'table',
                            'button_label' => '',
                            'collapsed' => '',
                            'sub_fields' => array(
                                0 => array(
                                    'key' => 'field_58eb6bd334c1c',
                                    'label' => __('Value', 'modularity-form-builder'),
                                    'name' => 'value',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'maxlength' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                ),
                            ),
                        ),
                        2 => array(
                            'key' => 'field_58eb6bd334c1d',
                            'label' => __('Required', 'modularity-form-builder'),
                            'name' => 'required',
                            'type' => 'true_false',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => 0,
                            'message' => __('Required', 'modularity-form-builder'),
                            'ui' => 0,
                            'ui_on_text' => '',
                            'ui_off_text' => '',
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
                6 => array(
                    'key' => '58eccdd75ad90',
                    'name' => 'file_upload',
                    'label' => 'File upload',
                    'display' => 'block',
                    'sub_fields' => array(
                        0 => array(
                            'key' => 'field_58ecce8a5ad93',
                            'label' => __('Field label', 'modularity-form-builder'),
                            'name' => 'label',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'maxlength' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                        ),
                        1 => array(
                            'key' => 'field_58eccde65ad91',
                            'label' => __('Type', 'modularity-form-builder'),
                            'name' => 'type',
                            'type' => 'radio',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'layout' => 'horizontal',
                            'choices' => array(
                                'single' => __('Single', 'modularity-form-builder'),
                                'multiple' => __('Multiple', 'modularity-form-builder'),
                            ),
                            'default_value' => '',
                            'other_choice' => 0,
                            'save_other_choice' => 0,
                            'allow_null' => 0,
                            'return_format' => 'value',
                        ),
                        2 => array(
                            'key' => 'field_58ece6685df9c',
                            'label' => __('Max number of files', 'modularity-form-builder'),
                            'name' => 'files_max',
                            'type' => 'number',
                            'instructions' => __('-1 for no limit', 'modularity-form-builder'),
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => -1,
                            'min' => '',
                            'max' => '',
                            'step' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                        ),
                        3 => array(
                            'key' => 'field_58ecce105ad92',
                            'label' => __('Allowed filetypes', 'modularity-form-builder'),
                            'name' => 'filetypes',
                            'type' => 'checkbox',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'layout' => 'vertical',
                            'choices' => array(
                                'video/*' => __('All video types', 'modularity-form-builder'),
                                'image/*' => __('All image types', 'modularity-form-builder'),
                                '.jpg' => __('jpg', 'modularity-form-builder'),
                                '.png' => __('png', 'modularity-form-builder'),
                                '.gif' => __('gif', 'modularity-form-builder'),
                                '.mov' => __('mov', 'modularity-form-builder'),
                                '.webm' => __('webm', 'modularity-form-builder'),
                                '.mp4' => __('mp4', 'modularity-form-builder'),
                                '.doc' => __('doc', 'modularity-form-builder'),
                                '.docx' => __('docx', 'modularity-form-builder'),
                                '.xls' => __('xls', 'modularity-form-builder'),
                                '.xlsx' => __('xlsx', 'modularity-form-builder'),
                                '.pdf' => __('pdf', 'modularity-form-builder'),
                            ),
                            'default_value' => array(
                            ),
                            'allow_custom' => 0,
                            'save_custom' => 0,
                            'toggle' => 0,
                            'return_format' => 'value',
                        ),
                        4 => array(
                            'key' => 'field_58ecd86751bf6',
                            'label' => __('Required', 'modularity-form-builder'),
                            'name' => 'required',
                            'type' => 'true_false',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => 0,
                            'message' => __('Required', 'modularity-form-builder'),
                            'ui' => 0,
                            'ui_on_text' => '',
                            'ui_off_text' => '',
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
                7 => array(
                    'key' => '597af62ef47e7',
                    'name' => 'custom_content',
                    'label' => 'Custom content',
                    'display' => 'block',
                    'sub_fields' => array(
                        0 => array(
                            'key' => 'field_597af6b1f47ea',
                            'label' => __('Content', 'modularity-form-builder'),
                            'name' => 'content',
                            'type' => 'wysiwyg',
                            'instructions' => __('Add custom content to the form. This will not be sent in e-mail messages.', 'modularity-form-builder'),
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'tabs' => 'all',
                            'toolbar' => 'full',
                            'media_upload' => 1,
                            'delay' => 0,
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
            ),
        ),
        2 => array(
            'key' => 'field_58f5c12da612a',
            'label' => __('Submission', 'modularity-form-builder'),
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
        ),
        3 => array(
            'key' => 'field_58eb3700191e7',
            'label' => __('Text on submit button', 'modularity-form-builder'),
            'name' => 'submit_button_text',
            'type' => 'text',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => 'Send',
            'maxlength' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
        ),
        4 => array(
            'key' => 'field_58eb7b11cc4f5',
            'label' => __('Subimission notice', 'modularity-form-builder'),
            'name' => 'subimission_notice',
            'type' => 'wysiwyg',
            'instructions' => __('Text to display when form is submitted.', 'modularity-form-builder'),
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'tabs' => 'all',
            'toolbar' => 'full',
            'media_upload' => 1,
            'default_value' => '',
            'delay' => 0,
        ),
        5 => array(
            'key' => 'field_58f5c029ee90a',
            'label' => __('Notifications', 'modularity-form-builder'),
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
        ),
        6 => array(
            'key' => 'field_58eb6ee89aa7c',
            'label' => __('Notifications on form submission', 'modularity-form-builder'),
            'name' => 'notify',
            'type' => 'repeater',
            'instructions' => __('Notifications will be sent to below added email addresses when receiving a new form submission.', 'modularity-form-builder'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'min' => 0,
            'max' => 0,
            'layout' => 'table',
            'button_label' => __('Add email', 'modularity-form-builder'),
            'collapsed' => '',
            'sub_fields' => array(
                0 => array(
                    'key' => 'field_58eb6f389aa7d',
                    'label' => __('Email address', 'modularity-form-builder'),
                    'name' => 'email',
                    'type' => 'email',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                ),
            ),
        ),
        7 => array(
            'key' => 'field_59720c161a3a1',
            'label' => __('Custom email subject', 'modularity-form-builder'),
            'name' => 'notification_custom_subject',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => __('Check this box if you want to enter a custom email subject.', 'modularity-form-builder'),
            'default_value' => 0,
            'ui' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
        ),
        8 => array(
            'key' => 'field_5972079df9f04',
            'label' => __('Email subject', 'modularity-form-builder'),
            'name' => 'notification_subject',
            'type' => 'text',
            'instructions' => __('Enter custom email subject. Default is "New form submission".', 'modularity-form-builder'),
            'required' => 1,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_59720c161a3a1',
                        'operator' => '==',
                        'value' => '1',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        9 => array(
            'key' => 'field_58f5d00332436',
            'label' => __('Notification message', 'modularity-form-builder'),
            'name' => 'notification_message',
            'type' => 'wysiwyg',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'tabs' => 'all',
            'toolbar' => 'full',
            'media_upload' => 1,
            'default_value' => '',
            'delay' => 0,
        ),
        10 => array(
            'key' => 'field_58f5b1a066797',
            'label' => __('Notification data', 'modularity-form-builder'),
            'name' => 'submission_notice_data',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => 1,
            'message' => __('Show submission data in notice content', 'modularity-form-builder'),
            'ui' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
        ),
        11 => array(
            'key' => 'field_58f5c0bbee90c',
            'label' => __('Sender copy', 'modularity-form-builder'),
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
        ),
        12 => array(
            'key' => 'field_58f5b1c266798',
            'label' => __('Allow sender copy', 'modularity-form-builder'),
            'name' => 'allow_sender_copy',
            'type' => 'true_false',
            'instructions' => __('Send copy of the submitted form data to the sender email.', 'modularity-form-builder'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => 0,
            'message' => __('Yes, allow user to get a copy of the submission', 'modularity-form-builder'),
            'ui' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
        ),
        13 => array(
            'key' => 'field_58f5d09142d94',
            'label' => __('Sender copy message', 'modularity-form-builder'),
            'name' => 'sender_copy_message',
            'type' => 'wysiwyg',
            'instructions' => __('The message that will be sent to the user together with a list of the submitted data.', 'modularity-form-builder'),
            'required' => 0,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_58f5b1c266798',
                        'operator' => '==',
                        'value' => '1',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'tabs' => 'all',
            'toolbar' => 'full',
            'media_upload' => 1,
            'default_value' => '',
            'delay' => 0,
        ),
        14 => array(
            'key' => 'field_58f5c0abee90b',
            'label' => __('Auto-reply', 'modularity-form-builder'),
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
        ),
        15 => array(
            'key' => 'field_58f5be7475dbf',
            'label' => __('Auto-reply', 'modularity-form-builder'),
            'name' => 'autoreply',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => 0,
            'message' => __('Send auto-reply on form submission', 'modularity-form-builder'),
            'ui' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
        ),
        16 => array(
            'key' => 'field_58f5bf7329b3f',
            'label' => __('Auto-reply subject', 'modularity-form-builder'),
            'name' => 'auto_reply_subject',
            'type' => 'text',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_58f5be7475dbf',
                        'operator' => '==',
                        'value' => '1',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'maxlength' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
        ),
        17 => array(
            'key' => 'field_58f5bea775dc0',
            'label' => __('Auto-reply content', 'modularity-form-builder'),
            'name' => 'auto_reply_content',
            'type' => 'wysiwyg',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_58f5be7475dbf',
                        'operator' => '==',
                        'value' => '1',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'tabs' => 'all',
            'toolbar' => 'full',
            'media_upload' => 1,
            'default_value' => '',
            'delay' => 0,
        ),
    ),
    'location' => array(
        0 => array(
            0 => array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'mod-form',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => 1,
    'description' => '',
));
}