<?php 

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group(array(
    'key' => 'group_58eb301ecb36a',
    'title' => __('Form', 'modularity-form-builder'),
    'fields' => array(
        0 => array(
            'key' => 'field_58f5c009ee909',
            'label' => __('Form fields', 'modularity-form-builder'),
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
        ),
        1 => array(
            'key' => 'field_58eb302883a68',
            'label' => __('Fields', 'modularity-form-builder'),
            'name' => 'form_fields',
            'type' => 'flexible_content',
            'value' => NULL,
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'button_label' => __('Add form field', 'modularity-form-builder'),
            'min' => 1,
            'max' => '',
            'layouts' => array(
                0 => array(
                    'key' => '58eb3033e588f',
                    'name' => 'sender',
                    'label' => __('Sender', 'modularity-form-builder'),
                    'display' => 'block',
                    'sub_fields' => array(
                        0 => array(
                            'key' => 'field_58eb3944f7086',
                            'label' => 'Fields to display',
                            'name' => 'fields',
                            'type' => 'checkbox',
                            'value' => NULL,
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '50',
                                'class' => '',
                                'id' => '',
                            ),
                            'layout' => 'vertical',
                            'choices' => array(
                                'firstname' => 'Firstname',
                                'lastname' => 'Lastname',
                                'email' => 'Email',
                                'phone' => 'Phone',
                                'address' => 'Address',
                            ),
                            'default_value' => array(
                                0 => 'firstname',
                                1 => 'lastname',
                                2 => 'email',
                            ),
                            'allow_custom' => 0,
                            'save_custom' => 0,
                            'toggle' => 0,
                            'return_format' => 'value',
                        ),
                        1 => array(
                            'key' => 'field_58eb3a9bf7087',
                            'label' => 'Required fields',
                            'name' => 'required_fields',
                            'type' => 'checkbox',
                            'value' => NULL,
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '50',
                                'class' => '',
                                'id' => '',
                            ),
                            'layout' => 'vertical',
                            'choices' => array(
                                'firstname' => 'Firstname',
                                'lastname' => 'Lastname',
                                'email' => 'Email',
                                'phone' => 'Phone',
                                'address' => 'Address',
                            ),
                            'default_value' => array(
                                0 => 'firstname',
                                1 => 'lastname',
                                2 => 'email',
                            ),
                            'allow_custom' => 0,
                            'save_custom' => 0,
                            'toggle' => 0,
                            'return_format' => 'value',
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
                1 => array(
                    'key' => '58eb3f2cd914a',
                    'name' => 'message',
                    'label' => __('Message', 'modularity-form-builder'),
                    'display' => 'block',
                    'sub_fields' => array(
                        0 => array(
                            'key' => 'field_58eb3f37d914b',
                            'label' => 'Field label',
                            'name' => 'label',
                            'type' => 'text',
                            'value' => NULL,
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => 'Message',
                            'maxlength' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                        ),
                        1 => array(
                            'key' => 'field_597b20d5392bc',
                            'label' => 'Field description',
                            'name' => 'description',
                            'type' => 'text',
                            'value' => NULL,
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        2 => array(
                            'key' => 'field_58eb3f5ed914c',
                            'label' => 'Required',
                            'name' => 'required',
                            'type' => 'true_false',
                            'value' => NULL,
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => 0,
                            'message' => 'Required field',
                            'ui' => 0,
                            'ui_on_text' => '',
                            'ui_off_text' => '',
                        ),
                        3 => array(
                            'key' => 'field_59b69b14e2abf',
                            'label' => 'Conditional logic',
                            'name' => 'conditional_logic',
                            'type' => 'true_false',
                            'value' => NULL,
                            'instructions' => 'Use conditional logic statement to display the field depending on other choices in the form. Works only with "Radio" form field type.',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'message' => 'Add conditional logic',
                            'default_value' => 0,
                            'ui' => 0,
                            'ui_on_text' => '',
                            'ui_off_text' => '',
                        ),
                        4 => array(
                            'key' => 'field_59b69b16e2ac0',
                            'label' => 'Conditonal field',
                            'name' => 'conditonal_field',
                            'type' => 'select',
                            'value' => NULL,
                            'instructions' => 'Display field if this value is selected.',
                            'required' => 0,
                            'conditional_logic' => array(
                                0 => array(
                                    0 => array(
                                        'field' => 'field_59b69b14e2abf',
                                        'operator' => '==',
                                        'value' => '1',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '50',
                                'class' => '',
                                'id' => '',
                            ),
                            'choices' => array(
                            ),
                            'default_value' => array(
                            ),
                            'allow_null' => 0,
                            'multiple' => 0,
                            'ui' => 0,
                            'ajax' => 0,
                            'return_format' => 'value',
                            'placeholder' => '',
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
                2 => array(
                    'key' => '58eb552a8189e',
                    'name' => 'input',
                    'label' => __('Input', 'modularity-form-builder'),
                    'display' => 'block',
                    'sub_fields' => array(
                        0 => array(
                            'key' => 'field_58eb55338189f',
                            'label' => 'Field label',
                            'name' => 'label',
                            'type' => 'text',
                            'value' => NULL,
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'maxlength' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                        ),
                        1 => array(
                            'key' => 'field_597b2100392bd',
                            'label' => 'Field description',
                            'name' => 'description',
                            'type' => 'text',
                            'value' => NULL,
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        2 => array(
                            'key' => 'field_58eb5547818a0',
                            'label' => 'Field value type',
                            'name' => 'value_type',
                            'type' => 'select',
                            'value' => NULL,
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'multiple' => 0,
                            'allow_null' => 0,
                            'choices' => array(
                                'text' => 'Text',
                                'number' => 'Number',
                                'email' => 'Email',
                                'tel' => 'Phone number',
                                'color' => 'Color',
                                'date' => 'Date',
                                'month' => 'Month',
                                'week' => 'Week',
                                'range' => 'Range',
                                'search' => 'Search',
                                'time' => 'Time',
                                'url' => 'Url',
                            ),
                            'default_value' => array(
                            ),
                            'ui' => 0,
                            'ajax' => 0,
                            'placeholder' => '',
                            'return_format' => 'value',
                        ),
                        3 => array(
                            'key' => 'field_58eb572440304',
                            'label' => 'Min value',
                            'name' => 'min_value',
                            'type' => 'number',
                            'value' => NULL,
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => array(
                                0 => array(
                                    0 => array(
                                        'field' => 'field_58eb5547818a0',
                                        'operator' => '==',
                                        'value' => 'number',
                                    ),
                                ),
                                1 => array(
                                    0 => array(
                                        'field' => 'field_58eb5547818a0',
                                        'operator' => '==',
                                        'value' => 'range',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '33.3333',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'min' => '',
                            'max' => '',
                            'step' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                        ),
                        4 => array(
                            'key' => 'field_58eb574140305',
                            'label' => 'Max value',
                            'name' => 'max_value',
                            'type' => 'number',
                            'value' => NULL,
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => array(
                                0 => array(
                                    0 => array(
                                        'field' => 'field_58eb5547818a0',
                                        'operator' => '==',
                                        'value' => 'number',
                                    ),
                                ),
                                1 => array(
                                    0 => array(
                                        'field' => 'field_58eb5547818a0',
                                        'operator' => '==',
                                        'value' => 'range',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '33.3333',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'min' => '',
                            'max' => '',
                            'step' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                        ),
                        5 => array(
                            'key' => 'field_58eb57a645640',
                            'label' => 'Step',
                            'name' => 'step',
                            'type' => 'number',
                            'value' => NULL,
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => array(
                                0 => array(
                                    0 => array(
                                        'field' => 'field_58eb5547818a0',
                                        'operator' => '==',
                                        'value' => 'number',
                                    ),
                                ),
                                1 => array(
                                    0 => array(
                                        'field' => 'field_58eb5547818a0',
                                        'operator' => '==',
                                        'value' => 'range',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '33.3333',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'min' => '',
                            'max' => '',
                            'step' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                        ),
                        6 => array(
                            'key' => 'field_58eb62d1ec890',
                            'label' => 'Min date',
                            'name' => 'min_value',
                            'type' => 'date_picker',
                            'value' => NULL,
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => array(
                                0 => array(
                                    0 => array(
                                        'field' => 'field_58eb5547818a0',
                                        'operator' => '==',
                                        'value' => 'date',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '50',
                                'class' => '',
                                'id' => '',
                            ),
                            'display_format' => 'Y-m-d',
                            'return_format' => 'Y-m-d',
                            'first_day' => 1,
                        ),
                        7 => array(
                            'key' => 'field_58eb62feec891',
                            'label' => 'Max date',
                            'name' => 'max_value',
                            'type' => 'date_picker',
                            'value' => NULL,
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => array(
                                0 => array(
                                    0 => array(
                                        'field' => 'field_58eb5547818a0',
                                        'operator' => '==',
                                        'value' => 'date',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '50',
                                'class' => '',
                                'id' => '',
                            ),
                            'display_format' => 'Y-m-d',
                            'return_format' => 'Y-m-d',
                            'first_day' => 1,
                        ),
                        8 => array(
                            'key' => 'field_58eb5614c5514',
                            'label' => 'Required',
                            'name' => 'required',
                            'type' => 'true_false',
                            'value' => NULL,
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => 0,
                            'message' => 'Required',
                            'ui' => 0,
                            'ui_on_text' => '',
                            'ui_off_text' => '',
                        ),
                        9 => array(
                            'key' => 'field_59b69ae3e2abd',
                            'label' => 'Conditional logic',
                            'name' => 'conditional_logic',
                            'type' => 'true_false',
                            'value' => NULL,
                            'instructions' => 'Use conditional logic statement to display the field depending on other choices in the form. Works only with "Radio" form field type.',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'message' => 'Add conditional logic',
                            'default_value' => 0,
                            'ui' => 0,
                            'ui_on_text' => '',
                            'ui_off_text' => '',
                        ),
                        10 => array(
                            'key' => 'field_59b69ae6e2abe',
                            'label' => 'Conditonal field',
                            'name' => 'conditonal_field',
                            'type' => 'select',
                            'value' => NULL,
                            'instructions' => 'Display field if this value is selected.',
                            'required' => 0,
                            'conditional_logic' => array(
                                0 => array(
                                    0 => array(
                                        'field' => 'field_59b69ae3e2abd',
                                        'operator' => '==',
                                        'value' => '1',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '50',
                                'class' => '',
                                'id' => '',
                            ),
                            'choices' => array(
                            ),
                            'default_value' => array(
                            ),
                            'allow_null' => 0,
                            'multiple' => 0,
                            'ui' => 0,
                            'ajax' => 0,
                            'return_format' => 'value',
                            'placeholder' => '',
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
                3 => array(
                    'key' => '58eb670839fee',
                    'name' => 'radio',
                    'label' => __('Radio', 'modularity-form-builder'),
                    'display' => 'block',
                    'sub_fields' => array(
                        0 => array(
                            'key' => 'field_58eb675039ff1',
                            'label' => 'Field label',
                            'name' => 'label',
                            'type' => 'text',
                            'value' => NULL,
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'maxlength' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                        ),
                        1 => array(
                            'key' => 'field_597b2112392be',
                            'label' => 'Field description',
                            'name' => 'description',
                            'type' => 'text',
                            'value' => NULL,
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        2 => array(
                            'key' => 'field_58eb670d39fef',
                            'label' => 'Field values',
                            'name' => 'values',
                            'type' => 'repeater',
                            'value' => NULL,
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'collapsed' => '',
                            'min' => 2,
                            'max' => 0,
                            'layout' => 'table',
                            'button_label' => '',
                            'sub_fields' => array(
                                0 => array(
                                    'key' => 'field_58eb672c39ff0',
                                    'label' => 'Value',
                                    'name' => 'value',
                                    'type' => 'text',
                                    'value' => NULL,
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'maxlength' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                ),
                            ),
                        ),
                        3 => array(
                            'key' => 'field_58eb699755795',
                            'label' => 'Required',
                            'name' => 'required',
                            'type' => 'true_false',
                            'value' => NULL,
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => 0,
                            'message' => 'Required',
                            'ui' => 0,
                            'ui_on_text' => '',
                            'ui_off_text' => '',
                        ),
                        4 => array(
                            'key' => 'field_59b69ac9e2abb',
                            'label' => 'Conditional logic',
                            'name' => 'conditional_logic',
                            'type' => 'true_false',
                            'value' => NULL,
                            'instructions' => 'Use conditional logic statement to display the field depending on other choices in the form. Works only with "Radio" form field type.',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'message' => 'Add conditional logic',
                            'default_value' => 0,
                            'ui' => 0,
                            'ui_on_text' => '',
                            'ui_off_text' => '',
                        ),
                        5 => array(
                            'key' => 'field_59b69acbe2abc',
                            'label' => 'Conditonal field',
                            'name' => 'conditonal_field',
                            'type' => 'select',
                            'value' => NULL,
                            'instructions' => 'Display field if this value is selected.',
                            'required' => 0,
                            'conditional_logic' => array(
                                0 => array(
                                    0 => array(
                                        'field' => 'field_59b69ac9e2abb',
                                        'operator' => '==',
                                        'value' => '1',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '50',
                                'class' => '',
                                'id' => '',
                            ),
                            'choices' => array(
                            ),
                            'default_value' => array(
                            ),
                            'allow_null' => 0,
                            'multiple' => 0,
                            'ui' => 0,
                            'ajax' => 0,
                            'return_format' => 'value',
                            'placeholder' => '',
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
                4 => array(
                    'key' => '58eb6b023b076',
                    'name' => 'checkbox',
                    'label' => __('Checkbox', 'modularity-form-builder'),
                    'display' => 'block',
                    'sub_fields' => array(
                        0 => array(
                            'key' => 'field_58eb6b023b077',
                            'label' => 'Field label',
                            'name' => 'label',
                            'type' => 'text',
                            'value' => NULL,
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'maxlength' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                        ),
                        1 => array(
                            'key' => 'field_597b211f392bf',
                            'label' => 'Field description',
                            'name' => 'description',
                            'type' => 'text',
                            'value' => NULL,
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        2 => array(
                            'key' => 'field_58eb6b023b078',
                            'label' => 'Field values',
                            'name' => 'values',
                            'type' => 'repeater',
                            'value' => NULL,
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'min' => 1,
                            'max' => 0,
                            'layout' => 'table',
                            'button_label' => '',
                            'collapsed' => '',
                            'sub_fields' => array(
                                0 => array(
                                    'key' => 'field_58eb6b023b079',
                                    'label' => 'Value',
                                    'name' => 'value',
                                    'type' => 'text',
                                    'value' => NULL,
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'maxlength' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                ),
                            ),
                        ),
                        3 => array(
                            'key' => 'field_58eb6b023b07a',
                            'label' => 'Required',
                            'name' => 'required',
                            'type' => 'true_false',
                            'value' => NULL,
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => 0,
                            'message' => 'Required',
                            'ui' => 0,
                            'ui_on_text' => '',
                            'ui_off_text' => '',
                        ),
                        4 => array(
                            'key' => 'field_59b69ab2e2ab9',
                            'label' => 'Conditional logic',
                            'name' => 'conditional_logic',
                            'type' => 'true_false',
                            'value' => NULL,
                            'instructions' => 'Use conditional logic statement to display the field depending on other choices in the form. Works only with "Radio" form field type.',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'message' => 'Add conditional logic',
                            'default_value' => 0,
                            'ui' => 0,
                            'ui_on_text' => '',
                            'ui_off_text' => '',
                        ),
                        5 => array(
                            'key' => 'field_59b69ab5e2aba',
                            'label' => 'Conditonal field',
                            'name' => 'conditonal_field',
                            'type' => 'select',
                            'value' => NULL,
                            'instructions' => 'Display field if this value is selected.',
                            'required' => 0,
                            'conditional_logic' => array(
                                0 => array(
                                    0 => array(
                                        'field' => 'field_59b69ab2e2ab9',
                                        'operator' => '==',
                                        'value' => '1',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '50',
                                'class' => '',
                                'id' => '',
                            ),
                            'choices' => array(
                            ),
                            'default_value' => array(
                            ),
                            'allow_null' => 0,
                            'multiple' => 0,
                            'ui' => 0,
                            'ajax' => 0,
                            'return_format' => 'value',
                            'placeholder' => '',
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
                5 => array(
                    'key' => '58eb6bd234c19',
                    'name' => 'select',
                    'label' => __('Select', 'modularity-form-builder'),
                    'display' => 'block',
                    'sub_fields' => array(
                        0 => array(
                            'key' => 'field_58eb6bd334c1a',
                            'label' => 'Field label',
                            'name' => 'label',
                            'type' => 'text',
                            'value' => NULL,
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'maxlength' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                        ),
                        1 => array(
                            'key' => 'field_597b2132392c0',
                            'label' => 'Field description',
                            'name' => 'description',
                            'type' => 'text',
                            'value' => NULL,
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        2 => array(
                            'key' => 'field_58eb6bd334c1b',
                            'label' => 'Field values',
                            'name' => 'values',
                            'type' => 'repeater',
                            'value' => NULL,
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'min' => 1,
                            'max' => 0,
                            'layout' => 'table',
                            'button_label' => '',
                            'collapsed' => '',
                            'sub_fields' => array(
                                0 => array(
                                    'key' => 'field_58eb6bd334c1c',
                                    'label' => 'Value',
                                    'name' => 'value',
                                    'type' => 'text',
                                    'value' => NULL,
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'maxlength' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                ),
                            ),
                        ),
                        3 => array(
                            'key' => 'field_58eb6bd334c1d',
                            'label' => 'Required',
                            'name' => 'required',
                            'type' => 'true_false',
                            'value' => NULL,
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => 0,
                            'message' => 'Required',
                            'ui' => 0,
                            'ui_on_text' => '',
                            'ui_off_text' => '',
                        ),
                        4 => array(
                            'key' => 'field_59b69a93e2ab7',
                            'label' => 'Conditional logic',
                            'name' => 'conditional_logic',
                            'type' => 'true_false',
                            'value' => NULL,
                            'instructions' => 'Use conditional logic statement to display the field depending on other choices in the form. Works only with "Radio" form field type.',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'message' => 'Add conditional logic',
                            'default_value' => 0,
                            'ui' => 0,
                            'ui_on_text' => '',
                            'ui_off_text' => '',
                        ),
                        5 => array(
                            'key' => 'field_59b69a96e2ab8',
                            'label' => 'Conditonal field',
                            'name' => 'conditonal_field',
                            'type' => 'select',
                            'value' => NULL,
                            'instructions' => 'Display field if this value is selected.',
                            'required' => 0,
                            'conditional_logic' => array(
                                0 => array(
                                    0 => array(
                                        'field' => 'field_59b69a93e2ab7',
                                        'operator' => '==',
                                        'value' => '1',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '50',
                                'class' => '',
                                'id' => '',
                            ),
                            'choices' => array(
                            ),
                            'default_value' => array(
                            ),
                            'allow_null' => 0,
                            'multiple' => 0,
                            'ui' => 0,
                            'ajax' => 0,
                            'return_format' => 'value',
                            'placeholder' => '',
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
                6 => array(
                    'key' => '58eccdd75ad90',
                    'name' => 'file_upload',
                    'label' => __('File upload', 'modularity-form-builder'),
                    'display' => 'block',
                    'sub_fields' => array(
                        0 => array(
                            'key' => 'field_58ecce8a5ad93',
                            'label' => 'Field label',
                            'name' => 'label',
                            'type' => 'text',
                            'value' => NULL,
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'maxlength' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                        ),
                        1 => array(
                            'key' => 'field_597b213f392c1',
                            'label' => 'Field description',
                            'name' => 'description',
                            'type' => 'text',
                            'value' => NULL,
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        2 => array(
                            'key' => 'field_58eccde65ad91',
                            'label' => 'Type',
                            'name' => 'type',
                            'type' => 'radio',
                            'value' => NULL,
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'choices' => array(
                                'single' => 'Single',
                                'multiple' => 'Multiple',
                            ),
                            'allow_null' => 0,
                            'other_choice' => 0,
                            'save_other_choice' => 0,
                            'default_value' => '',
                            'layout' => 'horizontal',
                            'return_format' => 'value',
                        ),
                        3 => array(
                            'key' => 'field_58ece6685df9c',
                            'label' => 'Max number of files',
                            'name' => 'files_max',
                            'type' => 'number',
                            'value' => NULL,
                            'instructions' => '-1 for no limit',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => -1,
                            'min' => '',
                            'max' => '',
                            'step' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                        ),
                        4 => array(
                            'key' => 'field_58ecce105ad92',
                            'label' => 'Allowed filetypes',
                            'name' => 'filetypes',
                            'type' => 'checkbox',
                            'value' => NULL,
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'choices' => array(
                                'video/*' => 'All video types',
                                'image/*' => 'All image types',
                                '.jpg' => 'jpg',
                                '.png' => 'png',
                                '.gif' => 'gif',
                                '.mov' => 'mov',
                                '.webm' => 'webm',
                                '.mp4' => 'mp4',
                                '.mp3' => 'mp3',
                                '.ogg' => 'ogg',
                                '.aac' => 'aac',
                                '.doc' => 'doc',
                                '.docx' => 'docx',
                                '.xls' => 'xls',
                                '.xlsx' => 'xlsx',
                                '.pdf' => 'pdf',
                            ),
                            'allow_custom' => 0,
                            'save_custom' => 0,
                            'default_value' => array(
                            ),
                            'layout' => 'vertical',
                            'toggle' => 0,
                            'return_format' => 'value',
                        ),
                        5 => array(
                            'key' => 'field_58ecd86751bf6',
                            'label' => 'Required',
                            'name' => 'required',
                            'type' => 'true_false',
                            'value' => NULL,
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'message' => 'Required',
                            'default_value' => 0,
                            'ui' => 0,
                            'ui_on_text' => '',
                            'ui_off_text' => '',
                        ),
                        6 => array(
                            'key' => 'field_59b69a7ae2ab5',
                            'label' => 'Conditional logic',
                            'name' => 'conditional_logic',
                            'type' => 'true_false',
                            'value' => NULL,
                            'instructions' => 'Use conditional logic statement to display the field depending on other choices in the form. Works only with "Radio" form field type.',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'message' => 'Add conditional logic',
                            'default_value' => 0,
                            'ui' => 0,
                            'ui_on_text' => '',
                            'ui_off_text' => '',
                        ),
                        7 => array(
                            'key' => 'field_59b69a7de2ab6',
                            'label' => 'Conditonal field',
                            'name' => 'conditonal_field',
                            'type' => 'select',
                            'value' => NULL,
                            'instructions' => 'Display field if this value is selected.',
                            'required' => 0,
                            'conditional_logic' => array(
                                0 => array(
                                    0 => array(
                                        'field' => 'field_59b69a7ae2ab5',
                                        'operator' => '==',
                                        'value' => '1',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '50',
                                'class' => '',
                                'id' => '',
                            ),
                            'choices' => array(
                            ),
                            'default_value' => array(
                            ),
                            'allow_null' => 0,
                            'multiple' => 0,
                            'ui' => 0,
                            'ajax' => 0,
                            'return_format' => 'value',
                            'placeholder' => '',
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
                7 => array(
                    'key' => '59b13312b61ac',
                    'name' => 'custom_content',
                    'label' => __('Custom content', 'modularity-form-builder'),
                    'display' => 'block',
                    'sub_fields' => array(
                        0 => array(
                            'key' => 'field_59b13312b61ad',
                            'label' => 'Content',
                            'name' => 'content',
                            'type' => 'wysiwyg',
                            'value' => NULL,
                            'instructions' => 'Add custom content to the form. This will not be sent in e-mail messages.',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'tabs' => 'all',
                            'toolbar' => 'full',
                            'media_upload' => 1,
                            'delay' => 0,
                        ),
                        1 => array(
                            'key' => 'field_59b134beb61b0',
                            'label' => 'Conditional logic',
                            'name' => 'conditional_logic',
                            'type' => 'true_false',
                            'value' => NULL,
                            'instructions' => 'Use conditional logic statement to display the field depending on other choices in the form. Works only with "Radio" form field type.',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'message' => 'Add conditional logic',
                            'default_value' => 0,
                            'ui' => 0,
                            'ui_on_text' => '',
                            'ui_off_text' => '',
                        ),
                        2 => array(
                            'key' => 'field_59b635765e86b',
                            'label' => 'Conditonal field',
                            'name' => 'conditonal_field',
                            'type' => 'select',
                            'value' => NULL,
                            'instructions' => 'Display field if this value is selected.',
                            'required' => 0,
                            'conditional_logic' => array(
                                0 => array(
                                    0 => array(
                                        'field' => 'field_59b134beb61b0',
                                        'operator' => '==',
                                        'value' => '1',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '50',
                                'class' => '',
                                'id' => '',
                            ),
                            'choices' => array(
                            ),
                            'default_value' => array(
                            ),
                            'allow_null' => 0,
                            'multiple' => 0,
                            'ui' => 0,
                            'ajax' => 0,
                            'return_format' => 'value',
                            'placeholder' => '',
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
            ),
        ),
        2 => array(
            'key' => 'field_58f5c12da612a',
            'label' => __('Submission', 'modularity-form-builder'),
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
        ),
        3 => array(
            'key' => 'field_58eb3700191e7',
            'label' => __('Text on submit button', 'modularity-form-builder'),
            'name' => 'submit_button_text',
            'type' => 'text',
            'value' => NULL,
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => 'Send',
            'maxlength' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
        ),
        4 => array(
            'key' => 'field_59df53ac189b8',
            'label' => __('Public act notice', 'modularity-form-builder'),
            'name' => 'submission_public_act',
            'type' => 'true_false',
            'value' => NULL,
            'instructions' => __('Adds a notice that informs the user that the submission will become a public act.', 'modularity-form-builder'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => __('Add public act notice', 'modularity-form-builder'),
            'default_value' => 1,
            'ui' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
        ),
        5 => array(
            'key' => 'field_58eb7b11cc4f5',
            'label' => __('Subimission notice', 'modularity-form-builder'),
            'name' => 'subimission_notice',
            'type' => 'wysiwyg',
            'value' => NULL,
            'instructions' => __('Text to display when form is submitted.', 'modularity-form-builder'),
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'tabs' => 'all',
            'toolbar' => 'full',
            'media_upload' => 1,
            'default_value' => '',
            'delay' => 0,
        ),
        6 => array(
            'key' => 'field_58f5c029ee90a',
            'label' => __('Notifications', 'modularity-form-builder'),
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
        ),
        7 => array(
            'key' => 'field_59a4259acfea0',
            'label' => __('Notifications on form submission', 'modularity-form-builder'),
            'name' => '',
            'type' => 'message',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => '',
            'new_lines' => 'wpautop',
            'esc_html' => 0,
        ),
        8 => array(
            'key' => 'field_58eb6ee89aa7c',
            'label' => __('Notify email addresses', 'modularity-form-builder'),
            'name' => 'notify',
            'type' => 'repeater',
            'value' => NULL,
            'instructions' => __('Notifications will be sent to below added email addresses when receiving a new form submission.', 'modularity-form-builder'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'collapsed' => '',
            'min' => 0,
            'max' => 0,
            'layout' => 'table',
            'button_label' => __('Add email', 'modularity-form-builder'),
            'sub_fields' => array(
                0 => array(
                    'key' => 'field_58eb6f389aa7d',
                    'label' => __('Email address', 'modularity-form-builder'),
                    'name' => 'email',
                    'type' => 'email',
                    'value' => NULL,
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                ),
            ),
        ),
        9 => array(
            'key' => 'field_59720c161a3a1',
            'label' => __('Custom email subject', 'modularity-form-builder'),
            'name' => 'notification_custom_subject',
            'type' => 'true_false',
            'value' => NULL,
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => __('Check this box if you want to enter a custom email subject.', 'modularity-form-builder'),
            'default_value' => 0,
            'ui' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
        ),
        10 => array(
            'key' => 'field_5972079df9f04',
            'label' => __('Email subject', 'modularity-form-builder'),
            'name' => 'notification_subject',
            'type' => 'text',
            'value' => NULL,
            'instructions' => __('Enter custom email subject. Default is "New form submission".', 'modularity-form-builder'),
            'required' => 1,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_59720c161a3a1',
                        'operator' => '==',
                        'value' => '1',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        11 => array(
            'key' => 'field_58f5d00332436',
            'label' => __('Notification message', 'modularity-form-builder'),
            'name' => 'notification_message',
            'type' => 'wysiwyg',
            'value' => NULL,
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'tabs' => 'all',
            'toolbar' => 'full',
            'media_upload' => 1,
            'default_value' => '',
            'delay' => 0,
        ),
        12 => array(
            'key' => 'field_58f5b1a066797',
            'label' => __('Notification data', 'modularity-form-builder'),
            'name' => 'submission_notice_data',
            'type' => 'true_false',
            'value' => NULL,
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => 1,
            'message' => __('Show submission data in notice content', 'modularity-form-builder'),
            'ui' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
        ),
        13 => array(
            'key' => 'field_58f5c0bbee90c',
            'label' => __('Sender copy', 'modularity-form-builder'),
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
        ),
        14 => array(
            'key' => 'field_58f5b1c266798',
            'label' => __('Allow sender copy', 'modularity-form-builder'),
            'name' => 'allow_sender_copy',
            'type' => 'true_false',
            'value' => NULL,
            'instructions' => __('Send copy of the submitted form data to the sender email.', 'modularity-form-builder'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => 0,
            'message' => __('Yes, allow user to get a copy of the submission', 'modularity-form-builder'),
            'ui' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
        ),
        15 => array(
            'key' => 'field_59a561ed8a256',
            'label' => __('Custom email subject for submission copy', 'modularity-form-builder'),
            'name' => 'copy_custom_subject',
            'type' => 'true_false',
            'value' => NULL,
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_58f5b1c266798',
                        'operator' => '==',
                        'value' => '1',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => __('Check this box if you want to enter a custom email subject.', 'modularity-form-builder'),
            'default_value' => 0,
            'ui' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
        ),
        16 => array(
            'key' => 'field_59a562508a257',
            'label' => __('Email subject', 'modularity-form-builder'),
            'name' => 'copy_subject',
            'type' => 'text',
            'value' => NULL,
            'instructions' => __('Enter custom email subject. Default is "Form submission copy".', 'modularity-form-builder'),
            'required' => 1,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_59a561ed8a256',
                        'operator' => '==',
                        'value' => '1',
                    ),
                    1 => array(
                        'field' => 'field_58f5b1c266798',
                        'operator' => '==',
                        'value' => '1',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        17 => array(
            'key' => 'field_58f5d09142d94',
            'label' => __('Sender copy message', 'modularity-form-builder'),
            'name' => 'sender_copy_message',
            'type' => 'wysiwyg',
            'value' => NULL,
            'instructions' => __('The message that will be sent to the user together with a list of the submitted data.', 'modularity-form-builder'),
            'required' => 0,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_58f5b1c266798',
                        'operator' => '==',
                        'value' => '1',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'tabs' => 'all',
            'toolbar' => 'full',
            'media_upload' => 1,
            'default_value' => '',
            'delay' => 0,
        ),
        18 => array(
            'key' => 'field_58f5c0abee90b',
            'label' => __('Auto-reply', 'modularity-form-builder'),
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
        ),
        19 => array(
            'key' => 'field_58f5be7475dbf',
            'label' => __('Auto-reply', 'modularity-form-builder'),
            'name' => 'autoreply',
            'type' => 'true_false',
            'value' => NULL,
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => 0,
            'message' => __('Send auto-reply on form submission', 'modularity-form-builder'),
            'ui' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
        ),
        20 => array(
            'key' => 'field_58f5bf7329b3f',
            'label' => __('Auto-reply subject', 'modularity-form-builder'),
            'name' => 'auto_reply_subject',
            'type' => 'text',
            'value' => NULL,
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_58f5be7475dbf',
                        'operator' => '==',
                        'value' => '1',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'maxlength' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
        ),
        21 => array(
            'key' => 'field_58f5bea775dc0',
            'label' => __('Auto-reply content', 'modularity-form-builder'),
            'name' => 'auto_reply_content',
            'type' => 'wysiwyg',
            'value' => NULL,
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_58f5be7475dbf',
                        'operator' => '==',
                        'value' => '1',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'tabs' => 'all',
            'toolbar' => 'full',
            'media_upload' => 1,
            'default_value' => '',
            'delay' => 0,
        ),
    ),
    'location' => array(
        0 => array(
            0 => array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'mod-form',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => 1,
    'description' => '',
));
}